export default {
  "SE" : "SEK",
  "NO" : "NOK",
  "DK" : "DKK",
  "GB" : "GBP",
  "US" : "USD",
  "FI" : "EUR",
  "US":	"USD",
  "SV":	"USD",
  "PA":	"USD",
  "EC":	"USD",
  "GU":	"USD",
  "PW":	"USD",
  "PR":	"USD",
  "ZW":	"USD",
  "AU":	"AUD",
  "CA":	"CAD",
  "NZ":	"NZD",
  "IN":	"INR",
  "ZA":	"ZAR",
  "NA":	"NAD",
  "BW":	"BWP",
  "ZW":	"ZWD",
  "SZ":	"SZL",
  "LS":	"LSL",
  "ZM":	"ZMF",
  "TZ":	"TZS",
  "KE":	"KES",
  "UG":	"UGX",
  "NG":	"NGN",
  "CM":	"XAF",
  "GH":	"GHS",
  "LR":	"LRD",
  "SL":	"SLL",
  "GM":	"GMD",
  "SC":	"SCR",
  "MU":	"MUR",
  "SH":	"SHP"
}
